language: node_js
node_js:
  - "12"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - git remote add upstream https://github.com/nelidiakonidze/universal.git
  - git fetch upstream master
  - yarn

script:
  - yarn lint
  - yarn test

deploy:
  - provider: script
    script: yarn deploy
    skip_cleanup: true
    on:
      branch: master

