rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0 #-> stylelint auto-fix
  # placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  # one-declaration-per-line: 1
  empty-line-between-blocks: 0 #-> stylelint auto-fix
  single-line-per-selector: 0 #-> stylelint auto-fix

  # Disallows
  # no-attribute-selectors: 0
  # no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  # no-combinators: 0
  # no-css-comments: 1
  # no-debug: 1
  # no-disallowed-properties: 0
  # no-duplicate-properties: 1
  # no-empty-rulesets: 1
  # no-extends: 0
  # no-ids: 1
  # no-important: 1
  # no-invalid-hex: 1
  # no-mergeable-selectors: 1
  # no-misspelled-properties: 1
  # no-qualifying-elements: 1
  # no-trailing-whitespace: 1
  no-trailing-zero: 0 #-> stylelint auto-fix
  # no-transition-all: 1
  # no-universal-selectors: 0
  # no-url-domains: 1
  # no-url-protocols: 1
  # no-vendor-prefixes: 1
  no-warn: 0
  # property-units: 0

  # Nesting
  # force-attribute-nesting: 1
  # force-element-nesting: 1
  # force-pseudo-nesting: 1

  # Name Formats
  # class-name-format: 1
  # function-name-format: 1
  # id-name-format: 0
  # mixin-name-format: 1
  # placeholder-name-format: 1
  # variable-name-format: 1

  # Style Guide
  # attribute-quotes: 1
  # bem-depth: 0
  # border-zero: 1
  # brace-style: 1
  # clean-import-paths: 1
  # empty-args: 1
  # hex-length: 1
  # hex-notation: 1
  # indentation: 1
  leading-zero: 0 #-> stylelint auto-fix
  nesting-depth: 0 #-> stylelint auto-fix
  property-sort-order: 0 #-> stylelint auto-fix
  # pseudo-element: 1
  # quotes: 1
  # shorthand-values: 1
  # url-quotes: 1
  # variable-for-property: 1
  zero-unit: 0 #-> stylelint auto-fix

  # Inner Spacing
  # space-after-comma: 1
  space-before-colon: 0 #-> stylelint auto-fix
  space-after-colon: 0 #-> stylelint auto-fix
  space-before-brace: 0 #-> stylelint auto-fix
  # space-before-bang: 1
  # space-after-bang: 1
  # space-between-parens: 1
  # space-around-operator: 1

  # Final Items
  # trailing-semicolon: 1
  # final-newline: 1